name: Publish
on:
  push:
    branches: [ "main" ]

jobs:
  publish_image:
    name: build and publish docker image
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build . -t voikyrioh/my-chess-game:latest
      - name: publish image
        run: |
          docker login -u voikyrioh -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push voikyrioh/my-chess-game:latest
  deploy:
    needs: publish_image
    name: deploy on prod
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -t rsa,ecdsa,ed25519 -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa -v "cd ${{ secrets.WORK_DIR }} && docker-compose down && docker-compose pull && docker-compose up -d && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
